#server
ACTIVE_PROFILE: prod
CONTAINER_PORT: 8085

#database
POSTGRESQL_HOST: 192.168.43.78
POSTGRESQL_PORT:  5432
POSTGRESQL_DATABASE:  docs
POSTGRESQL_USERNAME: ephi
POSTGRESQL_PASSWORD: 123

#mail
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: smssystem178@gmail.com
EMAIL_PASSWORD: ipnctkfeudlefyts
VERIFY_EMAIL_HOST: http://securedoc.com